Repository Workiva/sockjs_client_wrapper, pull requests merged in 2023-04, with the labels that each got.

#52 Fix CI: Disable beta channel in CI since it's Dart 3.0
  .github/workflows/dart_ci.yaml
Labels: semver: Patch, Merge Requirements Met, RM Ready

#51 Prepare for dart_dev v4.0.0
  pubspec.yaml
Labels: semver: Patch, Merge Requirements Met, RM Ready

#53 w_common v3 rollout - 1 of 2 raise max
  pubspec.yaml
Labels: semver: Patch, Merge Requirements Met, RM Ready

#55 RM-152148 Release sockjs_client_wrapper 1.1.12
  pubspec.yaml
Labels: type: Release, semver: Patch, Merge Requirements Met, RM Ready

#54 Null safety
  lib/src/client.dart
  lib/src/events.dart
  lib/src/js_interop.dart
  pubspec.yaml
  test/sockjs_client_wrapper_test.dart
  tool/dart_dev/config.dart
Labels: semver: Minor, Merge Requirements Met, RM Ready

#56 RM-188299 Release sockjs_client_wrapper 1.2.0
  CHANGELOG.md
  pubspec.yaml
Labels: type: Release, semver: Minor, Merge Requirements Met, RM Ready
